### ISSUE TITLE
Question about PCB

### ISSUE THREAD

**Issue by ATMEGA17** [thingler/esp32-pico-module#1]
Hello, Firs of all thankyou for your efforts i will try to make this module and fabricate it to do that in order to maintain the best performance for the antenna  i noticed you did not make a ground plane 
1 - do i have to make a ground plane ?
2 - what is the pcb thickness from wihch you calculated the wire width attached to the antenna via the capacitor to achieve 50ohm of impedance 
3 - can you please tell me if the results of your antenna is good ?
4 - can i replace your antenna with chip antenna ?

Thank you very much

**Comment by jarl-tornroos** [comment]
Hi, thanks for showing interest in my project!

The ground plane is not there because it’s only a two-layer board and quite crowded with traces. The PCB is ~1.6mm and the copper thickness is ~35µm. The bord is actually already using a chip antenna, 2450AT14A0100T. The antenna circuit design is taken from the datasheet, https://www.mouser.com/datasheet/2/611/2450AT14A0100-1519323.pdf

When I designed the PCB I tried to use a matching circuit from the datasheet but I realized that the signal is much better when connecting a 0 Ohm resistor for C3 and to leave L1 unconnected. I just today removed C3 and L1 from the design and pushed the changes.

The result of the antenna is okayish, not as good as for example the ESP32-PICO-KIT with the Pro Ant 440 antenna but maybe close to my Samsung S8. I’m no expert on antennas so I believe the circuit can be improved.

**Comment by jarl-tornroos** [comment]
Also, note that the ESP32-PICO-V3 has a build-in 50 Ohm output impedance circuit from the feed line.

**Comment by ATMEGA17** [comment]
Thank you so much for your answers and thank you for sharing the antenna link it was the missing part now after reading it every thing is clear  
for commercial and professional uses  I will use the esp32-wroom-32 for the project I am working on now  with its own PCB antenna after that I will certainly build your project test its performance  and keep you on updates
